### ISSUE TITLE
Chat fixes

### ISSUE THREAD

**Issue by arthurchaloin** [teksploit/client#86]
- [x] companion chat boxes z-index
- [x] companion box fix + display white on black
- [x] bubble displayed + room leave = exeption
- [x] chat box always displayed, show history btn

**Comment by paullaffitte** [comment]
"companion chat boxes z-index" seems to be already fixed. I can move everywhere, the bubble stay at the right place. 
![sans titre](https://user-images.githubusercontent.com/23403270/51995790-b40ce280-24b3-11e9-993c-bf8ca4c90c23.png)

**Comment by paullaffitte** [comment]
new display + raycast fixes

![image](https://user-images.githubusercontent.com/23403270/51996327-c9ced780-24b4-11e9-9971-0bd0bd3478b5.png)

**Comment by paullaffitte** [comment]
I saw no exception when switching between rooms with a chat message in the overlay

**Comment by paullaffitte** [comment]
![image](https://user-images.githubusercontent.com/23403270/51997793-bb35ef80-24b7-11e9-9403-664e5b7a4377.png)

![image](https://user-images.githubusercontent.com/23403270/51997811-c6891b00-24b7-11e9-9702-7eb371422510.png)
